language: java

before_install:
  - chmod +x mvnw

script: 
  - ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - mvn test

notifications:
  email:
    recipients:
      - akosruszka@gmail.com
    on_success: change
    on_failure: always