server:
  port: 9000
  error:
    include-stacktrace: always
    whitelabel:
      enabled: false
      
spring:
  devtools:
    restart:
      enabled: true
    
  h2:
    console:
      enabled: true
      path: /h2
      
  datasource:
    url: jdbc:h2:file:~/test
    username: admin
    password: pass
    driver-class-name: org.h2.Driver
    tomcat:
      connection-properties: useUnicode=true;characterEncoding=utf-8;